### ISSUE TITLE
Very small model when loaded into Cura

### ISSUE THREAD

**Issue by hernejj** [aaronnelson/PLA-Face-Shield#1]
Is the STL faulty? Do you know how I can scale it properly?

**Comment by aaronnelson** [comment]
It is an inch model, if it comes in as super small, you will need to scale to inches (2540%).  The final dimensions in mm should be a bounding box of 167.34 mm x 136.75 mm x 15.03 mm.

**Comment by hernejj** [comment]
The scale factor you provided seems to have worked. Thank you :)
